import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import WhiteButton from "../components/atoms/white-button/WhiteButton";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={`${styles.background} h-screen relative z-10`}>
          {/* TOPSIDE */}
          <div className="h-1/2 relative z-20 flex justify-center">
            <div className="absolute h-full w-full -top-24">
              <Image
                src="/assets/images/home-top.png"
                layout="fill"
                alt="home-background-top"
              />
            </div>
            <div className={`pt-10 h-fit`}>
              <Image
                src="/assets/svg/logo.svg"
                width="200"
                height="140"
                alt="logo"
              />
            </div>
          </div>

          {/* BOTTOMSIDE */}
          <div className="h-1/2 relative z-20 overflow-hidden flex justify-center items-end">
            <div className="absolute h-full w-full top-16">
              <Image
                src="/assets/images/home-bottom.png"
                layout="fill"
                alt="home-background-bottom"
              />
            </div>
            <div className="z-30 mb-10 flex flex-col items-center">
              <h1 className=" text-center text-5xl font-bold text-white">
                Create Animated <br />
                Greeting Cards
              </h1>
              <div className="w-3/4 mt-6">
                <Link href="/cards">
                  <WhiteButton label="Get Started" />
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
